### PR TITLE
Updating base url for centos7 repo

### PR DESCRIPTION
**Pull request by TeaJunk**
Refers to changes in documentation: https://github.com/fluent/fluent-bit-docs/commit/19f8489c2f9bd3ed90664be440543d08cf005720

### CODE REVIEW

**Comment by TeaJunk** [comment]
Otherwise the package can't be found
```bash
 msg: |-
    http://packages.fluentbit.io/centos/7/./td-agent-bit-1.3.11-1.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by orachide** [comment]
Thanks @TeaJunk , Done!!!

**Comment by TeaJunk** [comment]
Don't you mind tagging this version also? Would be much appreciated!

**Comment by orachide** [comment]
Tagged as 1.1.0

**Comment by TeaJunk** [comment]
Thanks!

**Pull request merged**
